(()=>{
const d=document,body=d.body,loader=d.querySelector('.loader'),menu=d.querySelector('.menu-toggle'),nav=d.querySelector('.site-nav'),canvas=d.querySelector('#strandCanvas');
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
addEventListener('load',()=>setTimeout(()=>loader?.classList.add('done'),reduce?0:550));
if(menu&&nav){menu.addEventListener('click',()=>{const open=!nav.classList.contains('open');nav.classList.toggle('open',open);menu.classList.toggle('open',open);menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation')}));}
const header=d.querySelector('.site-header');let ticking=false;function scrollUI(){const max=Math.max(1,d.documentElement.scrollHeight-innerHeight),p=Math.min(1,scrollY/max);body.style.setProperty('--scroll-progress',p);header?.classList.toggle('scrolled',scrollY>24);ticking=false}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(scrollUI);ticking=true}},{passive:true});scrollUI();
const reveals=[...d.querySelectorAll('.reveal')];if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{e.target.classList.toggle('visible',e.isIntersecting);e.target.classList.toggle('exit',!e.isIntersecting&&e.boundingClientRect.top<0)}),{threshold:.1,rootMargin:'-9% 0px -9% 0px'});reveals.forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i%6,5)*55}ms`;io.observe(el)})}else reveals.forEach(e=>e.classList.add('visible'));
if(canvas&&!reduce){const ctx=canvas.getContext('2d',{alpha:true});let w=0,h=0,dpr=1,t=0,raf;const resize=()=>{dpr=Math.min(devicePixelRatio||1,1.75);w=canvas.clientWidth;h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};const draw=()=>{t+=.005;ctx.clearRect(0,0,w,h);for(let s=0;s<6;s++){ctx.beginPath();const base=w*(.42+s*.075),amp=28+s*8;for(let i=0;i<=100;i++){const y=h*i/100,x=base+Math.sin(i*.09+t*(1+s*.07)+s)*amp+Math.sin(i*.025-t)*30;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=s%3===0?'rgba(216,92,58,.18)':s%3===1?'rgba(219,231,173,.2)':'rgba(23,19,17,.08)';ctx.lineWidth=s%2?1:1.4;ctx.stroke()}raf=requestAnimationFrame(draw)};addEventListener('resize',resize);resize();draw();addEventListener('pagehide',()=>cancelAnimationFrame(raf));}
if(innerWidth>900&&!reduce){addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')},{passive:true})}
const tilt=d.querySelectorAll('.service-card,.contact-tile,.journey-visual,.menu-visual');tilt.forEach(el=>{el.addEventListener('pointermove',e=>{if(innerWidth<800||reduce)return;const r=el.getBoundingClientRect(),x=e.clientX/r.width-r.left/r.width-.5,y=e.clientY/r.height-r.top/r.height-.5;el.style.transform=`perspective(900px) rotateX(${y*-3}deg) rotateY(${x*3}deg) translateY(-5px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
d.querySelectorAll('a[href*="wa.me"]').forEach(a=>a.setAttribute('aria-label','Book WE Hair Cube on WhatsApp'));d.querySelectorAll('a[href^="tel:"]').forEach(a=>a.setAttribute('aria-label','Call WE Hair Cube'));
})();